### ISSUE TITLE
[BUG]  BSDF constructor inconsistency

### ISSUE THREAD

**Issue by schunkes** [eradiate/eradiate#333] opened 2023-06-07 15:02 UTC
# Bug report

## Summary

There is an inconsistency in the constructor for the LambertianBSDF. When the reflectance is given as a dictionary, no unit needs to be specified and conversion to reflectance units is handled automatically. However, when the reflectance is given as a spectrum object, the unit must be added by the user. Otherwise the BSDF constructor will raise an error, citing incompatible units, DIMENSIONLESS instead of REFLECTANCE.

My suspicion is, that the converter that handles the dictionary automatically attaches the correct units.

## Description

*Please describe your issue in detail*

## Steps to reproduce

The first of the two assignments passes, the second raises an error.

```python
import eradiate.scenes as ertsc

ground_bsdf_dict = ertsc.bsdfs.LambertianBSDF(
    reflectance = {
        "type": "interpolated",
        "wavelengths": [440, 550, 620],
        "values": [0.067269, 0.096786, 0.125058]
    }
)

ground_bsdf_obj = ertsc.bsdfs.LambertianBSDF(
    reflectance=ertsc.spectra.InterpolatedSpectrum(
        wavelengths=[440, 550, 620], 
        values=[0.067269, 0.096786, 0.125058]
    )
)
```

## System configuration

*Please provide information regarding your system configuration*

- Operating system: ...
- Compiler: ...
- Python version: ... *(get it from `python --version)`*
- Eradiate version: ... *(get it from `eradiate show`)*

**Comment by leroyvn** [comment] 2023-06-08 09:34
Hi @schunkes, thanks for the report and reproducer. The problem here is that the default `quantity` field is set to `dimensionless`. I changed that from `None` because it was creating too much trouble. This broke the symmetry between the dict API and the constructor. I don't see an easy fix for this, so for now, I would leave this unfixed and require to set the `quantity` field:

```python
import eradiate.scenes as ertsc

ground_bsdf_dict = ertsc.bsdfs.LambertianBSDF(
    reflectance = {
        "type": "interpolated",
        "quantity": "reflectance",  # optional
        "wavelengths": [440, 550, 620],
        "values": [0.067269, 0.096786, 0.125058]
    }
)

ground_bsdf_obj = ertsc.bsdfs.LambertianBSDF(
    reflectance=ertsc.spectra.InterpolatedSpectrum(
        quantity="reflectance",
        wavelengths=[440, 550, 620], 
        values=[0.067269, 0.096786, 0.125058]
    )
)
```

**Closed** 2023-06-15 14:55 UTC
Labels: bug 🐛
